version: '3'
services:
 db:
  image: postgres
  volumes:
   - ./tmp/db:/var/lib/postgresql/data
 web:
  build: .
  command: bundle exec rails s -p 3456 -b '0.0.0.0'
  volumes:
   - .:/app
  ports:
   - "3456:3456"
  env_file:
  - .env
  depends_on:
   - db
